// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5l8mQkaZS6JImFEaMsAcdapRVLFwRMPM',
    appId: '1:144047848759:web:0e51fd8b457f33a6332eb2',
    messagingSenderId: '144047848759',
    projectId: 'fir-8a060',
    authDomain: 'fir-8a060.firebaseapp.com',
    storageBucket: 'fir-8a060.firebasestorage.app',
    measurementId: 'G-2BMVSH975G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9h7ALRdY7v_bFz2RIjQpahmszrihJEMg',
    appId: '1:144047848759:android:4ca33bf6ac494803332eb2',
    messagingSenderId: '144047848759',
    projectId: 'fir-8a060',
    storageBucket: 'fir-8a060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKPZA8Ep5Jrwl8fUFHszb14LUDPTQDu-g',
    appId: '1:144047848759:ios:fe21eb171568cccb332eb2',
    messagingSenderId: '144047848759',
    projectId: 'fir-8a060',
    storageBucket: 'fir-8a060.firebasestorage.app',
    iosBundleId: 'com.example.latihan5Firebase',
  );
}
